baseURL: https://blog.viticis.com/
languageCode: en-us
title: Red Coast
theme: hugo-PaperMod
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  enableGitInfo: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  displayFullLangName: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowToc: false
  comments: false
  assets:
    disableFingerprinting: false
  socialIcons:
    - name: Twitter
      url: 'https://twitter.com/viticis'
    - name: Github
      url: 'https://github.com/viticis'
    - name: RSS
      url: /index.xml
    - name: Email
      url: 'mailto:ryu@oever.cn'
    - name: Telegram
      url: 'https://t.me/viticis'
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: Home
      name: Home
      url: /
      weight: 1
    - identifier: archives
      name: Archives
      url: /archives
      weight: 2
#    - identifier: about
#      name: About
#      url: /about
#      weight: 3
taxonomies:
  category: categories
  tag: tags